
<head>
    <!-- Bootstrap 3.3.6 -->
    <?php Tag::css('bootstrap/css/bootstrap.min') ?>
    <meta charset=<?= APP_CHARSET ?> >
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Sisop | Dashboard</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- DataTables -->
    <?php Tag::css('plugins/datatables/dataTables.bootstrap') ?>
    <!-- jvectormap -->
    <?php Tag::css('plugins/jvectormap/jquery-jvectormap-1.2.2') ?>
    <!-- Theme style -->
    <?php Tag::css('dist/css/AdminLTE.min') ?>
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <?php Tag::css('dist/css/skins/_all-skins.min') ?>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <?= Html::includeCss() ?>
</head>
