<!-- jQuery 2.2.3 -->
<?= Tag::js('plugins/jQuery/jquery-2.2.3.min'); ?>
<!-- Bootstrap 3.3.6 -->
<?= Tag::js('bootstrap/js/bootstrap.min'); ?>
<!-- DataTables -->
<?= Tag::js('plugins/datatables/jquery.dataTables.min'); ?>
<?= Tag::js('plugins/datatables/dataTables.bootstrap.min'); ?>
<!-- FastClick -->
<?= Tag::js('plugins/fastclick/fastclick'); ?>
<!-- AdminLTE App -->
<?= Tag::js('dist/js/app.min'); ?>
<!-- Sparkline -->
<?= Tag::js('plugins/sparkline/jquery.sparkline.min'); ?>
<!-- jvectormap -->
<?= Tag::js('plugins/jvectormap/jquery-jvectormap-1.2.2.min'); ?>
<?= Tag::js('plugins/jvectormap/jquery-jvectormap-world-mill-en'); ?>
<!-- SlimScroll 1.3.0 -->
<?= Tag::js('plugins/slimScroll/jquery.slimscroll.min'); ?>
<!-- ChartJS 1.0.1 -->
<?= Tag::js('plugins/chartjs/Chart.min'); ?>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<?= Tag::js('dist/js/pages/dashboard2'); ?>
<!-- AdminLTE for demo purposes -->
<?= Tag::js('dist/js/demo'); ?>
